// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.RazorView
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Reflection;
    
    
    #line 1 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class _CreateOrEdit : ViewBase
    {
        public override string TransformText()
        {
            
            #line 13 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 var viewDataType = Model.ViewDataType; 
            
            #line default
            #line hidden
            
            #line 14 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 if(viewDataType != null) { 
            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 15 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.FullName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 17 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 } 
            
            #line default
            #line hidden
            this.Write("@* This partial view defines form fields that will appear when creating and editi" +
                    "ng entities *@\r\n\r\n<table id=\"myTb\" style=\"width: 100%; height: 100%\" cellpadding" +
                    "=\"1\" cellspacing=\"1\"\r\n    bgcolor=\"LightYellow\">\r\n");
            
            #line 22 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"

int i=0;
var propertyList=Model.ViewDataType.ViewModelProperties;
foreach (ViewModelProperty property in propertyList) {
    if (!property.IsPrimaryKey && !property.IsForeignKey) {
	if(property.Name.EndsWith("_EnumValue")){
		continue;	
	}

            
            #line default
            #line hidden
            
            #line 31 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 if(i % 2 ==0) { 
            
            #line default
            #line hidden
            this.Write("\t<tr>\r\n");
            
            #line 33 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 } 
            
            #line default
            #line hidden
            this.Write("<td style=\"width: 10%;\" align=\"left\" bgcolor=\"LightGray\">\r\n\t@Html.Label(\"");
            
            #line 35 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DisplayName));
            
            #line default
            #line hidden
            this.Write("\")\r\n</td>\r\n<td style=\"width: 2%\" bgcolor=\"LightGray\">\r\n        </td>\r\n<td style=\"" +
                    "width: 30%\" align=\"left\">\r\n\t");
            
            #line 40 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 if(property.IsEnum){ 
            
            #line default
            #line hidden
            this.Write("\t@Html.DropDownListFor(model => model.");
            
            #line 41 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("_EnumValue, ((IEnumerable<");
            
            #line 41 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));
            
            #line default
            #line hidden
            this.Write(">)ViewBag.Possible");
            
            #line 41 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(").Select(option => new SelectListItem\r\n\t{\r\n\t    Text = (option == null ? \"None\" :" +
                    " option.ToString()),\r\n\t    Value = ((int)option).ToString(),\r\n\t    Selected = (M" +
                    "odel != null) && ((int)option == Model.");
            
            #line 45 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("_EnumValue)\r\n\t}))\r\n\t<span style=\"color: red;\">@Html.ValidationMessageFor(model =>" +
                    " model.");
            
            #line 47 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("_EnumValue)</span>\r\n\t");
            
            #line 48 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 }else{ 
            
            #line default
            #line hidden
            this.Write("    @Html.EditorFor(model => model.");
            
            #line 49 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t<span style=\"color: red;\">@Html.ValidationMessageFor(model => model.");
            
            #line 50 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")</span>\r\n\t");
            
            #line 51 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 52 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 if(property.IsDateTime) {
            
            #line default
            #line hidden
            this.Write("\t<script language=\"javascript\">\r\n        $(\'#");
            
            #line 54 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\').datebox({\r\n            \r\n        });\r\n    </script>\r\n\t");
            
            #line 58 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 }else if(property.IsInt){ 
            
            #line default
            #line hidden
            this.Write("\t\t<script language=\"javascript\">\r\n        $(\'#");
            
            #line 60 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\').numberbox({\r\n            min:0\r\n        });\r\n    </script>\r\n\t");
            
            #line 64 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 }else if(property.IsDecimal){ 
            
            #line default
            #line hidden
            this.Write("\t\t<script language=\"javascript\">\r\n        $(\'#");
            
            #line 66 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\').numberbox({\r\n            min:0,\r\n\t\t\tprecision:2\r\n        });\r\n    </script>\r\n\t" +
                    "");
            
            #line 71 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n");
            
            #line 73 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 if((++i % 2 == 0)){ 
            
            #line default
            #line hidden
            this.Write("\t</tr>\r\n");
            
            #line 75 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"

}
    }
}

foreach (var relation in Model.RelatedEntities.Values) {

            
            #line default
            #line hidden
            
            #line 82 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 if(i % 2 ==0) { 
            
            #line default
            #line hidden
            this.Write("\t<tr>\r\n");
            
            #line 84 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 } 
            
            #line default
            #line hidden
            this.Write("<td style=\"width: 10%;\" align=\"left\" bgcolor=\"LightGray\">\r\n\t @Html.Label(\"");
            
            #line 86 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.DisplayName));
            
            #line default
            #line hidden
            this.Write("\")\r\n</td>\r\n<td style=\"width: 2%\" bgcolor=\"LightGray\">\r\n        </td>\r\n<td style=\"" +
                    "width: 30%\" align=\"left\">\r\n    @Html.DropDownListFor(model => model.");
            
            #line 91 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.Name));
            
            #line default
            #line hidden
            this.Write(", ((IEnumerable<");
            
            #line 91 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.FullName));
            
            #line default
            #line hidden
            this.Write(">)ViewBag.Possible");
            
            #line 91 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.RelationNamePlural));
            
            #line default
            #line hidden
            this.Write(").Select(option => new SelectListItem {\r\n        Text = (option == null ? \"None\" " +
                    ": option.Name), \r\n        Value = option.ID.ToString(),\r\n        Selected = (Mod" +
                    "el != null) && (option.ID == Model.");
            
            #line 94 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n    }), \"Choose...\")\r\n    <span style=\"color: red;\">@Html.ValidationMessageFor" +
                    "(model => model.");
            
            #line 96 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.Name));
            
            #line default
            #line hidden
            this.Write("ID)</span>\r\n</td>\r\n");
            
            #line 98 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 if((++i % 2 == 0)){ 
            
            #line default
            #line hidden
            this.Write("\t</tr>\r\n");
            
            #line 100 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"

}
}

            
            #line default
            #line hidden
            
            #line 104 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 if((++i % 2 == 0)){ 
            
            #line default
            #line hidden
            this.Write("\t</tr>\r\n");
            
            #line 106 "D:\TestWork\VSIX\MVCScaffolder\Generator\RazorView\_CreateOrEdit.t4"
 } 
            
            #line default
            #line hidden
            this.Write("</table>");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
    }
    
    #line default
    #line hidden
}
