// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.RazorView
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    
    
    #line 1 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class Delete : ViewBase
    {
        public override string TransformText()
        {
            
            #line 12 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
 var viewDataType = Model.ViewDataType; 
            
            #line default
            #line hidden
            
            #line 13 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
 if(viewDataType != null) { 
            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 14 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.FullName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 16 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
 } 
            
            #line default
            #line hidden
            this.Write("@{\r\n    ViewBag.Title = \"Delete\";\r\n\tLayout = \"~/Views/Shared/_LayoutEdit.cshtml\";" +
                    "\r\n}\r\n\r\n<h3>Are you sure you want to delete this?</h3>\r\n<fieldset>\r\n    <legend>");
            
            #line 24 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelName ?? String.Empty));
            
            #line default
            #line hidden
            this.Write("</legend>\r\n\t<table id=\"myTb\" style=\"width: 100%; height: 100%\" cellpadding=\"1\" ce" +
                    "llspacing=\"1\"\r\n    bgcolor=\"LightYellow\">\r\n");
            
            #line 27 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"

int i=0;
var propertyList=Model.ViewDataType.ViewModelProperties;
foreach (ViewModelProperty property in propertyList) {
    if (!property.IsPrimaryKey) {
	if(property.Name.EndsWith("_EnumValue")){
		continue;	
	}

            
            #line default
            #line hidden
            
            #line 36 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
 if(i % 2 ==0) { 
            
            #line default
            #line hidden
            this.Write("\t<tr>\r\n");
            
            #line 38 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
 } 
            
            #line default
            #line hidden
            this.Write("<td style=\"width: 10%;\" align=\"left\" bgcolor=\"LightGray\">\r\n\t@Html.Label(\"");
            
            #line 40 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DisplayName));
            
            #line default
            #line hidden
            this.Write("\")\r\n</td>\r\n<td style=\"width: 2%\" bgcolor=\"LightGray\">\r\n        </td>\r\n<td style=\"" +
                    "width: 30%\" align=\"left\">\t\r\n    @Html.DisplayFor(model => model.");
            
            #line 45 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n</td>\r\n");
            
            #line 47 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
 if((++i % 2 == 0)){ 
            
            #line default
            #line hidden
            this.Write("\t</tr>\r\n");
            
            #line 49 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
 } 
            
            #line default
            #line hidden
            
            #line 50 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
 }} if((++i % 2 == 0)){ 
            
            #line default
            #line hidden
            this.Write("\t</tr>\r\n");
            
            #line 52 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n</fieldset>\r\n@using (Ajax.BeginForm(\"Delete\",new AjaxOptions(){OnSucces" +
                    "s = \"showpage(\'/");
            
            #line 55 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Delete.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelName ?? String.Empty));
            
            #line default
            #line hidden
            this.Write("/Index\')\"})) {\r\n    <p>\r\n\t\t@Html.HiddenFor(model => model.ID)\r\n        <input typ" +
                    "e=\"submit\" value=\"Delete\" /> |\r\n    </p>\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
    }
    
    #line default
    #line hidden
}
