// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.RazorView
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    
    
    #line 1 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class Details : ViewBase
    {
        public override string TransformText()
        {
            
            #line 12 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
 var viewDataType = Model.ViewDataType; 
            
            #line default
            #line hidden
            
            #line 13 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
 if(viewDataType != null) { 
            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 14 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.FullName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 16 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
 } 
            
            #line default
            #line hidden
            this.Write("@{\r\n    ViewBag.Title = \"Details\";\r\n\tLayout = \"~/Views/Shared/_LayoutEdit.cshtml\"" +
                    ";\r\n}\r\n\r\n\r\n<fieldset>\r\n    <legend>");
            
            #line 24 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelName ?? String.Empty));
            
            #line default
            #line hidden
            this.Write("</legend>\r\n");
            
            #line 25 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"

foreach (ViewModelProperty property in Model.ViewDataType.ViewModelProperties) {
    if (!property.IsPrimaryKey && !property.IsForeignKey) {

            
            #line default
            #line hidden
            this.Write("\r\n    <div class=\"display-label\">");
            
            #line 30 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DisplayName));
            
            #line default
            #line hidden
            this.Write("</div>\r\n    <div class=\"display-field\">@Model.");
            
            #line 31 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("</div>\r\n");
            
            #line 32 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"

    }
}

            
            #line default
            #line hidden
            this.Write("</fieldset>\r\n<p>\r\n");
            
            #line 38 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
 if (!String.IsNullOrEmpty(Model.PrimaryKey)) { 
            
            #line default
            #line hidden
            this.Write("    @Html.ActionLink(\"Edit\", \"Edit\", new { id=Model.");
            
            #line 39 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PrimaryKey));
            
            #line default
            #line hidden
            this.Write(" }) |\r\n    @Html.ActionLink(\"Back to List\", \"Index\")\r\n");
            
            #line 41 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
 } else { 
            
            #line default
            #line hidden
            this.Write("    @Html.ActionLink(\"Edit\", \"Edit\", new { /* id=Model.PrimaryKey */ }) |\r\n    @H" +
                    "tml.ActionLink(\"Back to List\", \"Index\")\r\n");
            
            #line 44 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Details.t4"
 } 
            
            #line default
            #line hidden
            this.Write("</p>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
    }
    
    #line default
    #line hidden
}
