// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.RazorView
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    
    
    #line 1 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Edit.t4"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class Edit : ViewBase
    {
        public override string TransformText()
        {
            
            #line 12 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Edit.t4"
 var viewDataType = Model.ViewDataType; 
            
            #line default
            #line hidden
            
            #line 13 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Edit.t4"
 if(viewDataType != null) { 
            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 14 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Edit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.FullName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 16 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Edit.t4"
 } 
            
            #line default
            #line hidden
            this.Write("@{\r\n    ViewBag.Title = \"Edit\";\r\n\tLayout = \"~/Views/Shared/_LayoutEdit.cshtml\";\r\n" +
                    "}\r\n\r\n@using (Ajax.BeginForm(\"Edit\",new AjaxOptions(){OnSuccess = \"showpage(\'/");
            
            #line 22 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Edit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelName ?? String.Empty));
            
            #line default
            #line hidden
            this.Write("/Index\')\"})) {\r\n    @Html.ValidationSummary(true)\r\n    <fieldset>\r\n        <legen" +
                    "d>");
            
            #line 25 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Edit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelName ?? String.Empty));
            
            #line default
            #line hidden
            this.Write("</legend>\r\n\r\n        @Html.HiddenFor(model => model.");
            
            #line 27 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Edit.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PrimaryKey));
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n\t\t@Html.Partial(\"_CreateOrEdit\", Model)\r\n\r\n        <p>\r\n            <input t" +
                    "ype=\"submit\" value=\"Save\" />\r\n        </p>\r\n    </fieldset>\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
    }
    
    #line default
    #line hidden
}
