// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.RazorView
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Reflection;
    
    
    #line 1 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class Index : ViewBase
    {
        public override string TransformText()
        {
            
            #line 13 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 var viewDataType = Model.ViewDataType; 
            
            #line default
            #line hidden
            
            #line 14 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 if(viewDataType != null) { 
            
            #line default
            #line hidden
            
            #line 15 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 } 
            
            #line default
            #line hidden
            this.Write("@{\r\n    ViewBag.Title = \"Index\";\r\n\tLayout = \"~/Views/Shared/_LayoutList.cshtml\";\r" +
                    "\n}\r\n\r\n");
            
            #line 21 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"

List<ViewModelProperty> properties =Model.ViewDataType.ViewModelProperties;

            
            #line default
            #line hidden
            this.Write("@section htmlSearch{\r\n    <div id=\"p\">\r\n    </div>\r\n}\r\n@section htmlTable{\r\n\t<div" +
                    " id=\"");
            
            #line 29 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("_searchbox_div\" style=\"padding-top: 3px;\">\r\n\t    <input id=\"");
            
            #line 30 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("_ss\" />\r\n\t    <div id=\"");
            
            #line 31 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("_mm\" style=\"width: 120px; padding-top: 2px;\">\r\n\t    </div>\r\n\t</div>\r\n\t<table id=\"" +
                    "");
            
            #line 34 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("Table\"></table>\r\n}\r\n\r\n@section jsDatagrid{\r\n\t<script type=\"text/javascript\">\r\n\t  " +
                    "  $(document).ready(function () {\r\n\t\t\t$(\'#p\').load(\'@Url.Action(\"Search\")\');\r\n\t " +
                    "       $(\'#");
            
            #line 41 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("Table\').datagrid({\r\n\t            //title: \'");
            
            #line 42 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write(@" List',
	           	iconCls: 'icon-save',          
	            fitColumns: false,
				striped: true,
				sortName: 'CreatedOn',
				sortOrder: 'desc',
				remoteSort: true,
				fit: true,
				idField: 'ID',
				frozenColumns:[[
					{field: 'ID', checkbox: true}
				]],
	            nowrap: false,
	            url: '@Url.Action(""List"")',
	           	columns: [[
				");
            
            #line 57 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"

				var needComma = false;
				for (int i=0; i<properties.Count; i++){
					ViewModelProperty property = properties[i];
	    			if (!property.IsPrimaryKey && !property.IsForeignKey&&!property.IsEnum) {
				
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 63 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 if(needComma){ 
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 63 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 } 
            
            #line default
            #line hidden
            this.Write("{\r\n\t\t\t\t\t");
            
            #line 64 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 needComma=true; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tfield:\'");
            
            #line 65 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\',title: \'");
            
            #line 65 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DisplayName));
            
            #line default
            #line hidden
            this.Write("\',width: \'");
            
            #line 65 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.IsDateTime?100:80));
            
            #line default
            #line hidden
            this.Write("\'\r\n\t\t\t\t\t\t");
            
            #line 66 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 if(property.IsDateTime){  
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t,sortable:true,formatter: function (value) {\r\n\t\t\t\t\t\t\t\t\tif(value)\r\n\t      " +
                    "                  \t\t\treturn eval(\"new \" + value.substr(1, value.length - 2)).toL" +
                    "ocaleDateString();\r\n\t                   \t\t \t}\r\n\t\t\t\t\t\t");
            
            #line 71 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 }else if(property.IsRefType){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t,formatter: function (value) {\r\n\t\t\t\t\t\t\t\t\tif(value)\r\n\t                    " +
                    "    \t\t\treturn \'<span id=\'+ value.Code+\' >\'+value.Name+\'</span>\';\r\n\t             " +
                    "      \t\t \t}\r\n\t\t\t\t\t\t");
            
            #line 76 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t}\r\n\t\t\t\t");
            
            #line 78 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 }} 
            
            #line default
            #line hidden
            this.Write(@"				]],
	            pagination: true,
				rownumbers: true,
	            showFooter: true,
				toolbar:[{
	        		text:'新增',
	        		iconCls:'icon-add',
	        		handler:function(){
	            		showpage('@Url.Action(""Create"")');
	        		}
	   			},{
			        text:'修改',
			        iconCls:'icon-save',
			        handler:function(){
			            var row = $('#");
            
            #line 93 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write(@"Table').datagrid('getSelected');
						if(!row){
							alert('选择要修改的行');
							return;
						}
	                    var url = '@Url.Action(""Edit"",new {id=""_TOREPLACE_""})';
	                    url = url.replace('_TOREPLACE_', row.ID);
	                    showpage(url);
			        }
			    }, ");
            
            #line 102 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 if(Model.IsApprovalOrder){ 
            
            #line default
            #line hidden
            this.Write("\'-\', {\r\n\t                text: \'提交\',\r\n\t                iconCls: \'icon-print\',\r\n\t " +
                    "               handler: function () {\r\n\t                    var row = $(\'#");
            
            #line 106 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write(@"Table').datagrid('getSelected');
	                    if (!row) {
	                        alert('选择要修改的行');
	                        return;
	                    }
	                    var url = '@Url.Action(""Submit"",new {id=""_TOREPLACE_""})';
	                    url = url.replace('_TOREPLACE_', row.ID);
	                    showModalpage(url,'");
            
            #line 113 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EntityName));
            
            #line default
            #line hidden
            this.Write("\',\'");
            
            #line 113 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("Table\');\r\n\t                }\r\n\t            },");
            
            #line 115 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\'-\',{\r\n\t\t\t        text:\'删除\',\r\n\t\t\t        iconCls:\'icon-cut\',\r\n\t\t\t        handler:" +
                    "function(){\r\n\t\t\t            var row = $(\'#");
            
            #line 119 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write(@"Table').datagrid('getSelected');
						if(!row){
							alert('选择要删除的行');
							return;
						}
	                    var url = '@Url.Action(""Delete"",new {id=""_TOREPLACE_""})';
	                    url = url.replace('_TOREPLACE_', row.ID);
	                    showpage(url);
			        }
	    		}, '-', {
                    text: '高级查询',
                    iconCls: 'icon-search',
                    handler: function () {
                        collapse();
                    }
                }],
	            onDblClickRow: function (rowIndex, rowData) {
	                var url = '@Url.Action(""Details"",new {id=""_TOREPLACE_""})';
	                url = url.replace('_TOREPLACE_', rowData.ID);
	                showpage(url);
	            }
	        });
	    });
		$(document).ready(function () {
			var fields = $('#");
            
            #line 143 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("Table\').datagrid(\'getColumnFields\');\r\n\t\t    for (var i = 0; i < fields.length; i+" +
                    "+) {\r\n\t\t        var opts = $(\'#");
            
            #line 145 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("Table\').datagrid(\'getColumnOption\', fields[i]);\r\n\t\t        var muit = \"<div name=" +
                    "\'\" + fields[i] + \"\'>\" + opts.title + \"</div>\";\r\n\t\t        $(\'#");
            
            #line 147 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("_mm\').html($(\'#");
            
            #line 147 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("_mm\').html() + muit);\r\n\t\t    }\r\n\t\t    $(\'#");
            
            #line 149 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("_ss\').searchbox({\r\n\t\t        width: 300,\r\n\t\t        searcher: function (value, na" +
                    "me) {\r\n\t\t\t\t\tvar params = {};\r\n\t\t            if (value) {\r\n\t\t                para" +
                    "ms[name] = value;\r\n\t\t                $(\'#");
            
            #line 155 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("Table\').datagrid(\'options\').queryParams = params;\r\n\t\t                $(\'#");
            
            #line 156 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("Table\').datagrid(\'reload\');\r\n\t\t            }else{\r\n\t\t\t\t\t\t$(\'#");
            
            #line 158 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("Table\').datagrid(\'options\').queryParams = params;\r\n\t\t                $(\'#");
            
            #line 159 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("Table\').datagrid(\'reload\');\r\n\t\t\t\t\t}\r\n\t\t        },\r\n\t\t        menu: \'#");
            
            #line 162 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("_mm\',\r\n\t\t        prompt: \'请输入查询条件\'\r\n\t\t    });\r\n\r\n\t\t    $(\'#");
            
            #line 166 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\RazorView\Index.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDataType.Name));
            
            #line default
            #line hidden
            this.Write("_searchbox_div\').appendTo(\'.datagrid-toolbar\');\r\n\t\t});\r\n\t</script>\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
    }
    
    #line default
    #line hidden
}
