// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator
{
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    
    #line 1 "D:\TestWork\VSIX\MVCScaffolder\Generator\Test.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class Test : Generator.EFRepository.RepositoryBase
    {
        public override string TransformText()
        {
            this.Write(" \r\n");
            
            #line 11 "D:\TestWork\VSIX\MVCScaffolder\Generator\Test.tt"

   // insert your template code here the tempalte code will be syntaxhighlighted 
   // and you will have intellisense for all namespaces in the full edition
   string Greeting = "Hello";

            
            #line default
            #line hidden
            this.Write("// This is the output code from your template\r\n// you only get syntax-highlightin" +
                    "g here - not intellisense\r\nnamespace MyNameSpace{\r\n  class MyGeneratedClass{\r\n  " +
                    "   static void main (string[] args){\r\n\t\t");
            
            #line 21 "D:\TestWork\VSIX\MVCScaffolder\Generator\Test.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DbContextNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 22 "D:\TestWork\VSIX\MVCScaffolder\Generator\Test.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelTypeNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 23 "D:\TestWork\VSIX\MVCScaffolder\Generator\Test.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.RepositoryNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n       System.Console.WriteLine(\"");
            
            #line 24 "D:\TestWork\VSIX\MVCScaffolder\Generator\Test.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Greeting));
            
            #line default
            #line hidden
            this.Write(", the time is now: ");
            
            #line 24 "D:\TestWork\VSIX\MVCScaffolder\Generator\Test.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(System.DateTime.Now.ToString()));
            
            #line default
            #line hidden
            this.Write("\");\r\n     }\r\n  }\r\n}\r\n \r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 29 "D:\TestWork\VSIX\MVCScaffolder\Generator\Test.tt"

  // Insert any template procedures here
  void foo(){}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
