// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.EFRepository
{
    using System.Linq;
    using System;
    
    
    #line 1 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class Repository : RepositoryBase
    {
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data;\r\nusing Syste" +
                    "m.Data.Entity;\r\nusing System.Linq;\r\nusing System.Linq.Expressions;\r\nusing System" +
                    ".Web;\r\n");
            
            #line 12 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 foreach(var ns in new[] { Model.ModelTypeNamespace, Model.DbContextNamespace }.Where(x => !string.IsNullOrEmpty(x) && (x != Model.RepositoryNamespace)).Distinct()) { 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 13 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(ns));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 14 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 16 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.RepositoryNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{ \r\n");
            
            #line 18 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 
    var modelType = Model.ModelType; 
    var modelName = Model.ModelName; 
    var modelNamePlural = Model.ModelTypePluralized; 
    var contextName = Model.ContextType; 
    var primaryKeyProperty =Model.PrimaryKeyProperty;
    var isObjectContext = false;

            
            #line default
            #line hidden
            this.Write("    public class ");
            
            #line 26 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("Repository : I");
            
            #line 26 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("Repository\r\n    {\r\n        ");
            
            #line 28 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(contextName));
            
            #line default
            #line hidden
            this.Write(" context = new ");
            
            #line 28 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(contextName));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\n        public IQueryable<");
            
            #line 30 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write("> All\r\n        {\r\n            get { return context.");
            
            #line 32 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write("; }\r\n        }\r\n\r\n        public IQueryable<");
            
            #line 35 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write("> AllIncluding(params Expression<Func<");
            
            #line 35 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write(", object>>[] includeProperties)\r\n        {\r\n            IQueryable<");
            
            #line 37 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write("> query = context.");
            
            #line 37 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write(";\r\n            foreach (var includeProperty in includeProperties) {\r\n            " +
                    "    query = query.Include(includeProperty);\r\n            }\r\n            return q" +
                    "uery;\r\n        }\r\n\r\n        public ");
            
            #line 44 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write(" Find(");
            
            #line 44 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyProperty));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n");
            
            #line 46 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 if(isObjectContext) { 
            
            #line default
            #line hidden
            this.Write("            return context.");
            
            #line 47 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write(".Single(x => x.");
            
            #line 47 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PrimaryKey));
            
            #line default
            #line hidden
            this.Write(" == id);\r\n");
            
            #line 48 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 } else { 
            
            #line default
            #line hidden
            this.Write("            return context.");
            
            #line 49 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write(".Find(id);\r\n");
            
            #line 50 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public void InsertOrUpdate(");
            
            #line 53 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 53 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 55 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 55 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PrimaryKey));
            
            #line default
            #line hidden
            this.Write(" == default(");
            
            #line 55 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyProperty));
            
            #line default
            #line hidden
            this.Write(")) {\r\n                // New entity\r\n");
            
            #line 57 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 if(primaryKeyProperty == "System.Guid") { 
            
            #line default
            #line hidden
            this.Write("               \r\n");
            
            #line 59 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 } 
            
            #line default
            #line hidden
            
            #line 60 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 if(isObjectContext) { 
            
            #line default
            #line hidden
            this.Write("                context.");
            
            #line 61 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write(".AddObject(");
            
            #line 61 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 62 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 } else { 
            
            #line default
            #line hidden
            this.Write("                context.");
            
            #line 63 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write(".Add(");
            
            #line 63 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 64 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("            } else {\r\n                // Existing entity\r\n");
            
            #line 67 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 if(isObjectContext) { 
            
            #line default
            #line hidden
            this.Write("                context.");
            
            #line 68 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write(".Attach(");
            
            #line 68 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n                context.ObjectStateManager.ChangeObjectState(");
            
            #line 69 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(", EntityState.Modified);\r\n");
            
            #line 70 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 } else { 
            
            #line default
            #line hidden
            this.Write("                context.Entry(");
            
            #line 71 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(").State = EntityState.Modified;\r\n");
            
            #line 72 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n\r\n        public void Delete(");
            
            #line 76 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyProperty));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n");
            
            #line 78 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 if(isObjectContext) { 
            
            #line default
            #line hidden
            this.Write("            var ");
            
            #line 79 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(" = context.");
            
            #line 79 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write(".Single(x => x.");
            
            #line 79 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PrimaryKey));
            
            #line default
            #line hidden
            this.Write(" == id);\r\n            context.");
            
            #line 80 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write(".DeleteObject(");
            
            #line 80 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 81 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 } else { 
            
            #line default
            #line hidden
            this.Write("            var ");
            
            #line 82 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(" = context.");
            
            #line 82 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write(".Find(id);\r\n            context.");
            
            #line 83 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNamePlural));
            
            #line default
            #line hidden
            this.Write(".Remove(");
            
            #line 83 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 84 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public void Save()\r\n        {\r\n            context.SaveChang" +
                    "es();\r\n        }\r\n\r\n        public void Dispose() \r\n        {\r\n            conte" +
                    "xt.Dispose();\r\n        }\r\n    }\r\n\r\n    public interface I");
            
            #line 98 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("Repository : IDisposable\r\n    {\r\n        IQueryable<");
            
            #line 100 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write("> All { get; }\r\n        IQueryable<");
            
            #line 101 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write("> AllIncluding(params Expression<Func<");
            
            #line 101 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write(", object>>[] includeProperties);\r\n        ");
            
            #line 102 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write(" Find(");
            
            #line 102 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyProperty));
            
            #line default
            #line hidden
            this.Write(" id);\r\n        void InsertOrUpdate(");
            
            #line 103 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 103 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n        void Delete(");
            
            #line 104 "D:\TestWork\VSIX\MVCScaffolder\Generator\EFRepository\Repository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyProperty));
            
            #line default
            #line hidden
            this.Write(" id);\r\n        void Save();\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
    }
    
    #line default
    #line hidden
}
