// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.Controller
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text.RegularExpressions;
    using System;
    
    
    #line 1 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class ControllerWithRepository : ControllerBase
    {
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Collections.Specia" +
                    "lized;\r\nusing System.Linq;\r\nusing System.Linq.Dynamic;\r\nusing System.Web;\r\nusing" +
                    " System.Web.Mvc;\r\n");
            
            #line 16 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 if(!string.IsNullOrEmpty(Model.ModelTypeNamespace)) { 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 17 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelTypeNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 18 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 19 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.RepositoryNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\r\nnamespace ");
            
            #line 22 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Namespace+".Controllers"));
            
            #line default
            #line hidden
            this.Write("\r\n{   \r\n");
            
            #line 24 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
  
	var modelType = Model.ModelType; 
    var modelName = Model.ModelName; 
    var modelNamePlural = Model.ModelTypePluralized; 
    var contextName = Model.ContextType; 
    var primaryKeyProperty =Model.PrimaryKeyProperty;
	var modelVariable = modelName.ToLower(); 
	var routingName = Model.RoutingName;

	var relatedEntities = Model.RelatedEntities;
	var modelEnumTypes = Model.EnumTypeProperties;

            
            #line default
            #line hidden
            this.Write("    public partial class ");
            
            #line 36 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ControllerName));
            
            #line default
            #line hidden
            this.Write(" : Controller\r\n    {\r\n");
            
            #line 38 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var repository in Model.Repositories.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\tprivate readonly I");
            
            #line 39 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(repository.RepositoryTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 39 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(repository.VariableName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 40 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t// If you are using Dependency Injection, you can delete the following construc" +
                    "tor\r\n        public ");
            
            #line 42 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ControllerName));
            
            #line default
            #line hidden
            this.Write("() : this(");
            
            #line 42 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", Model.Repositories.Values.Select(x => "new " + x.RepositoryTypeName + "()"))));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n        }\r\n\r\n        public ");
            
            #line 46 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ControllerName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 46 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", Model.Repositories.Values.Select(x => "I" + x.RepositoryTypeName + " " + x.VariableName))));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 48 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var repository in Model.Repositories.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tthis.");
            
            #line 49 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(repository.VariableName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 49 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(repository.VariableName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 50 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        //\r\n        // GET: /");
            
            #line 54 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write("/\r\n\r\n        public ViewResult Index()\r\n        {\r\n");
            
            #line 58 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"

	var includeExpression = String.Join(", ", relatedEntities.Values.Select(x => String.Format("{0} => {0}.{1}", modelVariable, x.Name)));
	if (!string.IsNullOrEmpty(includeExpression)) {
		includeExpression = "Including(" + includeExpression + ")";
	}

            
            #line default
            #line hidden
            this.Write("            return View();\r\n        }\r\n\t\t\r\n\t\t//\r\n\t\t// POST: /");
            
            #line 68 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write(@"/List
		[HttpPost]
		public JsonResult List(int page,int rows,string sort, string order)
		{
			try{
				var cols = new string[] { ""page"", ""rows"", ""sort"", ""order"" };
                NameValueCollection nvc = Request.Form;

                var col = nvc.AllKeys.Except(cols).FirstOrDefault();
				
				var ");
            
            #line 78 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("List = ");
            
            #line 78 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".All");
            
            #line 78 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(includeExpression));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\r\n                if (!string.IsNullOrEmpty(col))\r\n                {\r\n    " +
                    "                var cType = typeof(");
            
            #line 82 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(").GetProperty(col).PropertyType;\r\n                    if (cType.IsGenericType && " +
                    "cType.GetGenericTypeDefinition() == typeof(Nullable<>) && cType.GetGenericArgume" +
                    "nts()[0] == typeof(DateTime))\r\n                    {\r\n                        ");
            
            #line 85 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("List = ");
            
            #line 85 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("List.Where(string.Format(\"{0}=@0\", col), DateTime.Parse(nvc[col]));\r\n            " +
                    "        }\r\n                    else if (cType.IsValueType || cType == typeof(str" +
                    "ing))\r\n                    {\r\n\t\t\t\t\t\t");
            
            #line 89 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("List = ");
            
            #line 89 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("List.Where(string.Format(\"{0}=@0\", col), nvc[col]);\r\n                    }\r\n     " +
                    "               else\r\n                    {\r\n                        ");
            
            #line 93 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("List = ");
            
            #line 93 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("List.Where(string.Format(\"{0}.Code=@0\", col), nvc[col]);\r\n                    }\r\n" +
                    "\r\n                }\r\n\t\t\t\t\r\n\t\t\t\tvar total = ");
            
            #line 98 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("List.Count();\r\n\t\t\t\treturn Json(new { total = total, rows = ");
            
            #line 99 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("List.OrderBy(sort + \" \" + order).Skip((page - 1) * rows).Take(rows) });\r\n\t\t\t}\r\n\t\t" +
                    "\tcatch(Exception ex){\r\n\t\t\t\tthrow;\r\n\t\t\t}\r\n\t\t}\r\n\r\n        //\r\n        // GET: /");
            
            #line 107 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write("/Details/5\r\n\r\n        public ViewResult Details(");
            
            #line 109 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyProperty));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            return View(");
            
            #line 111 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".Find(id));\r\n        }\r\n\r\n        //\r\n        // GET: /");
            
            #line 115 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n\r\n        public ActionResult Create()\r\n        {\r\n");
            
            #line 119 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEntity in relatedEntities.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tViewBag.Possible");
            
            #line 120 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write("s = ");
            
            #line 120 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[relatedEntity.Name].VariableName));
            
            #line default
            #line hidden
            this.Write(".All;\r\n");
            
            #line 121 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 122 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEnum in modelEnumTypes.Values ){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tViewBag.Possible");
            
            #line 123 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.Name));
            
            #line default
            #line hidden
            this.Write(" = Enum.GetValues(typeof (");
            
            #line 123 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(")).Cast<");
            
            #line 123 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t");
            
            #line 124 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("            return View();\r\n        } \r\n\t\tpublic ActionResult Search()\r\n        {" +
                    "\r\n            ");
            
            #line 129 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEntity in relatedEntities.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tViewBag.Possible");
            
            #line 130 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write("s = ");
            
            #line 130 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[relatedEntity.Name].VariableName));
            
            #line default
            #line hidden
            this.Write(".All;\r\n");
            
            #line 131 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 132 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEnum in modelEnumTypes.Values ){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tViewBag.Possible");
            
            #line 133 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.Name));
            
            #line default
            #line hidden
            this.Write(" = Enum.GetValues(typeof (");
            
            #line 133 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(")).Cast<");
            
            #line 133 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t");
            
            #line 134 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("            return View();\r\n        }\r\n        //\r\n        // POST: /");
            
            #line 138 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n\r\n        [HttpPost]\r\n        public ActionResult Create(");
            
            #line 141 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 141 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (ModelState.IsValid) {\r\n                ");
            
            #line 144 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".InsertOrUpdate(");
            
            #line 144 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n                ");
            
            #line 145 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".Save();\r\n                return PartialView(\"Index\");\r\n            } else {\r\n ");
            
            #line 148 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEntity in relatedEntities.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tViewBag.Possible");
            
            #line 149 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write("s = ");
            
            #line 149 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[relatedEntity.Name].VariableName));
            
            #line default
            #line hidden
            this.Write(".All;\r\n");
            
            #line 150 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 151 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEnum in modelEnumTypes.Values ){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tViewBag.Possible");
            
            #line 152 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.Name));
            
            #line default
            #line hidden
            this.Write(" = Enum.GetValues(typeof (");
            
            #line 152 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(")).Cast<");
            
            #line 152 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t");
            
            #line 153 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\treturn PartialView(");
            
            #line 154 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t}\r\n        }\r\n        \r\n        //\r\n        // GET: /");
            
            #line 159 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write("/Edit/5\r\n \r\n        public ActionResult Edit(");
            
            #line 161 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyProperty));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n ");
            
            #line 163 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEntity in relatedEntities.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tViewBag.Possible");
            
            #line 164 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write("s = ");
            
            #line 164 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[relatedEntity.Name].VariableName));
            
            #line default
            #line hidden
            this.Write(".All;\r\n");
            
            #line 165 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 166 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEnum in modelEnumTypes.Values ){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tViewBag.Possible");
            
            #line 167 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.Name));
            
            #line default
            #line hidden
            this.Write(" = Enum.GetValues(typeof (");
            
            #line 167 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(")).Cast<");
            
            #line 167 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t");
            
            #line 168 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("             return View(");
            
            #line 169 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".Find(id));\r\n        }\r\n\r\n        //\r\n        // POST: /");
            
            #line 173 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write("/Edit/5\r\n\r\n        [HttpPost]\r\n        public ActionResult Edit(");
            
            #line 176 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 176 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (ModelState.IsValid) {\r\n                ");
            
            #line 179 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".InsertOrUpdate(");
            
            #line 179 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n                ");
            
            #line 180 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".Save();\r\n                return PartialView(\"Index\");\r\n            } else {\r\n ");
            
            #line 183 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEntity in relatedEntities.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tViewBag.Possible");
            
            #line 184 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write("s = ");
            
            #line 184 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[relatedEntity.Name].VariableName));
            
            #line default
            #line hidden
            this.Write(".All;\r\n");
            
            #line 185 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 186 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEnum in modelEnumTypes.Values ){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tViewBag.Possible");
            
            #line 187 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.Name));
            
            #line default
            #line hidden
            this.Write(" = Enum.GetValues(typeof (");
            
            #line 187 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(")).Cast<");
            
            #line 187 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t");
            
            #line 188 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\treturn PartialView(");
            
            #line 189 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t}\r\n        }\r\n\t\t");
            
            #line 192 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 if(Model.IsApprovalOrder){ 
            
            #line default
            #line hidden
            this.Write("\t\t//\r\n        // GET: /");
            
            #line 194 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write("/Submit/5\r\n \r\n        public ActionResult Submit(");
            
            #line 196 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyProperty));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n\t\t\tvar ");
            
            #line 198 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 198 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".Find(id);\r\n ");
            
            #line 199 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEntity in relatedEntities.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tViewBag.Possible");
            
            #line 200 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write("s = ");
            
            #line 200 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[relatedEntity.Name].VariableName));
            
            #line default
            #line hidden
            this.Write(".All;\r\n");
            
            #line 201 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 202 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEnum in modelEnumTypes.Values ){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tViewBag.Possible");
            
            #line 203 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.Name));
            
            #line default
            #line hidden
            this.Write(" = Enum.GetValues(typeof (");
            
            #line 203 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(")).Cast<");
            
            #line 203 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(">()\r\n\t\t\t\t.Select(option => new SelectListItem\r\n\t\t\t\t{\r\n\t\t\t\t\tText = option.ToString" +
                    "(),\r\n                \tValue = ((int)option).ToString(),\r\n                \tSelect" +
                    "ed = (");
            
            #line 208 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(" != null) && ((int)option == ");
            
            #line 208 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 208 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.ValueName));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t});\r\n\t\t\t");
            
            #line 210 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("             return View(");
            
            #line 211 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\t\t\r\n\t\t//\r\n        // POST: /");
            
            #line 215 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write("/Submit/5\r\n\r\n        [HttpPost]\r\n        public ActionResult Submit(");
            
            #line 218 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 218 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (ModelState.IsValid) {\r\n                ");
            
            #line 221 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".InsertOrUpdate(");
            
            #line 221 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n                ");
            
            #line 222 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".Save();\r\n                return PartialView(\"Index\");\r\n            } else {\r\n ");
            
            #line 225 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEntity in relatedEntities.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tViewBag.Possible");
            
            #line 226 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.Name));
            
            #line default
            #line hidden
            this.Write("s = ");
            
            #line 226 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[relatedEntity.Name].VariableName));
            
            #line default
            #line hidden
            this.Write(".All;\r\n");
            
            #line 227 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 228 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var relatedEnum in modelEnumTypes.Values ){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tViewBag.Possible");
            
            #line 229 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.Name));
            
            #line default
            #line hidden
            this.Write(" = Enum.GetValues(typeof (");
            
            #line 229 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(")).Cast<");
            
            #line 229 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEnum.TypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t");
            
            #line 230 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\treturn PartialView(");
            
            #line 231 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t}\r\n        }\r\n\t\t\r\n\t\t");
            
            #line 235 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("        //\r\n        // GET: /");
            
            #line 237 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write("/Delete/5\r\n \r\n        public ActionResult Delete(");
            
            #line 239 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyProperty));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            return View(");
            
            #line 241 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".Find(id));\r\n        }\r\n\r\n        //\r\n        // POST: /");
            
            #line 245 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(routingName));
            
            #line default
            #line hidden
            this.Write("/Delete/5\r\n\r\n        [HttpPost, ActionName(\"Delete\")]\r\n        public ActionResul" +
                    "t DeleteConfirmed(");
            
            #line 248 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyProperty));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            ");
            
            #line 250 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".Delete(id);\r\n            ");
            
            #line 251 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Repositories[Model.ModelName].VariableName));
            
            #line default
            #line hidden
            this.Write(".Save();\r\n\r\n            return PartialView(\"Index\");\r\n        }\r\n\r\n        protec" +
                    "ted override void Dispose(bool disposing)\r\n        {\r\n            if (disposing)" +
                    " {\r\n");
            
            #line 259 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 foreach(var repository in Model.Repositories.Values) { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 260 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(repository.VariableName));
            
            #line default
            #line hidden
            this.Write(".Dispose();\r\n");
            
            #line 261 "E:\SVN\MVCProj\domasmvc\MVCScaffolder\Generator\Controller\ControllerWithRepository.t4"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n            base.Dispose(disposing);\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
    }
    
    #line default
    #line hidden
}
